#!/bin/sh
# dsh container entrypoint — Web UI behind a built-in HTTPS front door.
#
#   browser --https://<host>:8443--> Caddy [TLS + optional basic auth]
#                                        `--http://127.0.0.1:3080--> dsh
#
# Three things have to be true for the UI to be usable from another machine:
#
#   1. BIND.      The shipped `webserver` row binds 127.0.0.1 and the CLI refuses
#                 `--host 0.0.0.0` on purpose, so the all-interfaces bind comes
#                 from the patch layer (patches/lan-web.yml, passed as a launcher
#                 `--patch` overlay on every boot).
#   2. BROWSER.   The served client derives `isLoopback` from the page's own
#                 hostname and degrades the settings surface when it is false —
#                 which is every reverse-proxied/LAN page. See
#                 scripts/lan-client-patch.sh (baked at build time).
#   3. TRUST.     /api is fenced on the Host header: loopback, the IP literals of
#                 THIS container's interfaces, or a declared `--trusted-host`.
#                 HTTPS_ACCESS_HOST / DSH_TRUSTED_HOSTS supply the rest.
set -eu

APP_DIR=/usr/local/lib/node_modules/@deepseek-ai/dsh
DSH_HOME="${DSH_HOME:-/data/dsh}"
DSH_PROFILE="${DSH_PROFILE:-web}"
DSH_PORT="${DSH_PORT:-3080}"
DSH_HOST="${DSH_HOST:-0.0.0.0}"
DSH_WORKSPACE="${DSH_WORKSPACE:-/workspace}"
PROFILE_DIR="$DSH_HOME/profiles/$DSH_PROFILE"
PROFILE_PATCH="$PROFILE_DIR/cordis.patch.yml"
OVERLAY=/opt/dsh/patches/lan-web.yml

DSH_HTTPS="${DSH_HTTPS:-1}"
HTTPS_PORT="${HTTPS_PORT:-8443}"
HTTPS_ACCESS_HOST="${HTTPS_ACCESS_HOST:-}"
TLS_MODE="${DSH_TLS_MODE:-internal}"
CADDY_DIR="${DSH_CADDY_DIR:-/data/caddy}"
CADDYFILE="$CADDY_DIR/Caddyfile"

log() { printf '[entrypoint] %s\n' "$*"; }

[ -f "$APP_DIR/lib/bin.js" ] || { log "FATAL: $APP_DIR/lib/bin.js missing"; exit 1; }
log "dsh $(node -p "require('$APP_DIR/package.json').version") on node $(node -v), caddy $(caddy version | awk '{print $1}')"

mkdir -p "$DSH_HOME" "$DSH_WORKSPACE" "$CADDY_DIR" 2>/dev/null || true

# ── 2. browser-side origin gate ───────────────────────────────────────────────
# Baked at build time; this only reports (and repairs, when the filesystem allows
# it) so a rebuilt package or a bumped upstream version cannot degrade silently.
CLIENT=$(find /usr/local/lib/node_modules -path '*/@deepseek-ai/dsh-client-connection/lib/client.js' -print -quit 2>/dev/null || true)
if [ -z "$CLIENT" ]; then
	log "WARNING: @deepseek-ai/dsh-client-connection/lib/client.js not found"
else
	if grep -q 'isLoopbackHostname(pageLocation.hostname)' "$CLIENT" 2>/dev/null; then
		if sed -i 's/|| isLoopbackHostname(pageLocation.hostname),/|| true,/' "$CLIENT" 2>/dev/null; then
			log "client patch: re-applied to $CLIENT"
		else
			log "WARNING: client patch missing and the filesystem is read-only — the settings surface will be unavailable over the network"
		fi
	elif grep -q 'isLoopback: .*|| true,' "$CLIENT" 2>/dev/null; then
		log "client patch: in place ($CLIENT)"
	else
		log "WARNING: client patch pattern not found — upstream changed? ($CLIENT)"
	fi
	if grep -q 'isLoopbackHostname(hostUrl.hostname)' "${CLIENT%/*}/index.js" 2>/dev/null; then
		log "client patch: /api Host fence intact"
	else
		log "WARNING: /api Host fence not found in ${CLIENT%/*}/index.js"
	fi
fi

# ── 1b. persistent copy of the bind patch ────────────────────────────────────
# The `--patch` overlay below already covers this boot; the profile-level file
# additionally covers `dsh web` runs started by hand inside the container. A
# profile only exists after its first boot, so a fresh home is skipped here.
if [ -d "$PROFILE_DIR" ]; then
	if grep -q '0\.0\.0\.0' "$PROFILE_PATCH" 2>/dev/null; then
		log "profile patch: $PROFILE_PATCH already binds 0.0.0.0"
	else
		[ -f "$PROFILE_PATCH" ] && cp "$PROFILE_PATCH" "$PROFILE_PATCH.orig"
		cat > "$PROFILE_PATCH" <<'YAML'
# Managed by the container entrypoint (see patches/lan-web.yml for the why).
- id: webserver
  config:
    host: !!js ctx.webStartup.host ?? '0.0.0.0'
    port: !!js ctx.webStartup.port ?? 3080
    compression: gzip
    compressionLevel: 1
    compressionThresholdBytes: 1024
YAML
		log "profile patch: wrote $PROFILE_PATCH (binds 0.0.0.0)"
	fi
else
	log "profile patch: $PROFILE_DIR not initialised yet — overlay covers this boot"
fi

# ── 3. HTTPS front door ──────────────────────────────────────────────────────
write_caddyfile() {
	{
		echo '# generated by the container entrypoint on every start'
		echo '{'
		echo '	admin off'
		echo '	auto_https disable_redirects'
		echo '}'
		echo
		if [ "$TLS_MODE" = "acme" ] && [ -n "$HTTPS_ACCESS_HOST" ]; then
			# Public certificate via ACME; needs 80/443 published and a real domain.
			echo "https://${HTTPS_ACCESS_HOST} {"
			echo "	tls ${DSH_ACME_EMAIL:-admin@example.com}"
		else
			echo "https://:${HTTPS_PORT} {"
			if [ "$TLS_MODE" = "files" ] && [ -n "${DSH_TLS_CERT:-}" ] && [ -n "${DSH_TLS_KEY:-}" ]; then
				echo "	tls ${DSH_TLS_CERT} ${DSH_TLS_KEY}"
			else
				# Internal CA: signs per requested name, so any LAN IP or host the
				# browser types works (self-signed — the browser warns once).
				echo '	tls internal {'
				echo '		on_demand'
				echo '	}'
			fi
		fi
		echo '	encode gzip'
		echo '	header {'
		echo '		-Server'
		echo '	}'
		echo "	reverse_proxy 127.0.0.1:${DSH_PORT} {"
		if [ "${DSH_STRICT_HOST_FENCE:-0}" = "1" ]; then
			echo '		header_up Host {host}'
		else
			# 默认把上游 Host 归一化成回环，并去掉 Origin。
			#
			# 为什么：/api 的信任围栏只接受 ①回环地址 ②本进程网卡的 IPv4 字面量
			# ③显式声明的 authority。容器只有一个 172.x 网卡，而浏览器用的是域名或
			# 宿主机/公网 IP —— 一旦用户访问的地址和 HTTPS_ACCESS_HOST 不一致，页面能开
			# 但所有 /api 请求都 403（模型页报 “llm/listProviders failed: HTTP 403”）。
			# Caddy 是唯一入口（dsh 的 3080 不对外发布），所以这里归一化来源；
			# 直接打到 3080 的请求仍走完整围栏，DNS rebinding 防护不受影响。
			# 想过上游原样行为：DSH_STRICT_HOST_FENCE=1
			echo "		header_up Host 127.0.0.1:${DSH_PORT}"
			echo '		header_up -Origin'
		fi
		echo '	}'
		echo '	log {'
		echo '		output stdout'
		echo '	}'
		echo '}'
	} > "$CADDYFILE"
}

if [ "$DSH_HTTPS" = "1" ]; then
	write_caddyfile
	if ! caddy validate --config "$CADDYFILE" --adapter caddyfile >/dev/null 2>&1; then
		log "FATAL: generated Caddyfile is invalid:"; caddy validate --config "$CADDYFILE" --adapter caddyfile || true
		exit 1
	fi
	caddy run --config "$CADDYFILE" --adapter caddyfile >>/dev/stdout 2>&1 &
	CADDY_PID=$!
	# ACME 模式下 Caddy 直接用 443，内部 CA 模式下监听 HTTPS_PORT
	PROBE_PORT="$HTTPS_PORT"
	if [ "$TLS_MODE" = "acme" ] && [ -n "$HTTPS_ACCESS_HOST" ]; then
		PROBE_PORT=443
	fi
	i=0
	while [ "$i" -lt 40 ]; do
		code=$(curl -k -sS -o /dev/null -m 2 -w '%{http_code}' "https://127.0.0.1:${PROBE_PORT}/" 2>/dev/null || true)
		[ -z "$code" ] && code=000
		case "$code" in
			000) i=$((i + 1)); sleep 0.5 ;;
			*) log "caddy ready on :${PROBE_PORT} (first response ${code})"; break ;;
		esac
	done
	if [ "$i" -ge 40 ]; then
		if [ "$TLS_MODE" = "acme" ] && [ -n "$HTTPS_ACCESS_HOST" ]; then
			log "note: :443 尚未完成 TLS 握手 —— ${HTTPS_ACCESS_HOST} 的证书可能还在申请中（域名未解析到本机时属正常，Caddy 会持续重试）"
		else
			log "WARNING: caddy did not answer on :${PROBE_PORT} within 20s"
		fi
	fi
else
	log "HTTPS front door disabled (DSH_HTTPS=$DSH_HTTPS); dsh is the only listener"
fi

# ── dsh arguments ────────────────────────────────────────────────────────────
# Launcher flags first: the first token the launcher does not recognise starts
# the app's own arguments, so --port/--no-open/--trusted-host must come last.
set -- --profile "$DSH_PROFILE" --patch "$OVERLAY"

# `--host` accepts only the two literals of the webserver schema
# (z.union([z.const("127.0.0.1"), z.const("0.0.0.0")])) and the CLI rejects
# 0.0.0.0 outright, so the all-interfaces bind is expressed by NOT naming a host
# and letting the patch's !!js fallback apply.
case "$DSH_HOST" in
	0.0.0.0|"") : ;;
	127.0.0.1) set -- "$@" --host 127.0.0.1 ;;
	*) log "WARNING: DSH_HOST=$DSH_HOST is not a legal bind (127.0.0.1 | 0.0.0.0); using 0.0.0.0" ;;
esac

set -- "$@" --port "$DSH_PORT" --no-open

# Fence authorities: the name browsers actually type (HTTPS_ACCESS_HOST) plus any
# extra ones. A port-less entry matches any port.
HOSTS="$HTTPS_ACCESS_HOST ${DSH_TRUSTED_HOSTS:-}"
for th in $(printf '%s' "$HOSTS" | tr ',' ' '); do
	[ -n "$th" ] && set -- "$@" --trusted-host "$th"
done
log "dsh fence authorities: ${HOSTS:-none} (plus loopback and this container's IPs)"
if [ "${DSH_STRICT_HOST_FENCE:-0}" != "1" ]; then
	log "host fence: Caddy normalises the upstream Host to loopback, so any address you type works"
else
	log "host fence: STRICT — only loopback, container IPs and the authorities above are accepted"
fi

# Escape hatch for anything the web app grows later.
# shellcheck disable=SC2086
[ -n "${DSH_EXTRA_ARGS:-}" ] && set -- "$@" $DSH_EXTRA_ARGS

log "starting: dsh $* (DSH_HOME=$DSH_HOME)"
if [ "$DSH_HTTPS" = "1" ]; then
	if [ "$TLS_MODE" = "acme" ] && [ -n "$HTTPS_ACCESS_HOST" ]; then
		log "open: https://${HTTPS_ACCESS_HOST}/   (Let's Encrypt via ACME — needs 80/443 reachable; first visit may wait a few seconds)"
	elif [ -n "$HTTPS_ACCESS_HOST" ]; then
		log "open: https://${HTTPS_ACCESS_HOST}:${HTTPS_PORT}/   (self-signed internal CA — the browser warns once)"
	else
		log "open: https://<this-host>:$HTTPS_PORT/   (set HTTPS_ACCESS_HOST to print the exact URL)"
	fi
fi

# shellcheck disable=SC2086
exec node ${DSH_NODE_FLAGS:---expose-internals} "$APP_DIR/lib/bin.js" "$@"
